### ISSUE TITLE
Rename to ImageFiltering?

### ISSUE THREAD

**Issue by kmsquire** [JuliaImages/ImageFiltering.jl#1]
`ImagesFiltering` sounds a little awkward to me--how about renaming to `ImageFiltering`?

Just a suggestion.

**Comment by timholy** [comment]
I agree it's awkward, and originally I called it `ImageFiltering`.

The fundamenta problem is that `ImagesMeta` exports a type called `ImageMeta`, and so on. (Although I'm not actually sure there's another "so on.")

**Comment by timholy** [comment]
I should clarify that I don't like the current situation either, so I am hoping this discussion leads to a better solution. It seems like there should be a way to solve this. Maybe rename that package `ImageMetadata`?

**Comment by mronian** [comment]
`ImageMetadata` seems better as `Meta` has other meanings too :)

**Comment by timholy** [comment]
OK, I'll explore a rename.

**Comment by andreasnoack** [comment]
Following up on https://github.com/JuliaLang/julia/issues/18384#issuecomment-245387949. Maybe drop the "image" part if the functionality is not restricted to images.

**Comment by timholy** [comment]
I thought about `ArrayFiltering` too. But there's also the question of "why not put it all in DSP.jl"? To which the reply is, "because there are certain conventions, e.g., regarding padding, that are almost universal when working with images that are less common elsewhere."

Fundamentally I'm not sure what to do. A simple rename would be easy, and I'm willing to do that, but having invested so much time in this package already---and the fact that finishing it is blocking to release an entire new Images rewrite---a big redesign of the (new) API is probably not on the table.

**Comment by andreasnoack** [comment]
Makes sense. It would be great to find the right common API but it can often be time consuming and you might end up with something that is less convenient for the applications you care about. Feel free to ignore my comment. I probably won't be a user any time soon anyway. Just felt it was a shame if people couldn't find the good stuff because of the name.
